{{- range .Values.envoyProxies }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "gateway-system.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
spec:
  provider:
    type: {{ .provider.type }}
    {{- if eq .provider.type "Kubernetes" }}
    kubernetes:
      envoyService:
        type: {{ .provider.kubernetes.envoyService.type }}
        {{- with .provider.kubernetes.envoyService.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}
{{- end }}
