{{- range .Values.gatewayClasses }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .name }}
  labels:
    {{- include "gateway-system.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
spec:
  controllerName: {{ .controllerName }}
  {{- with .parametersRef }}
  parametersRef:
    group: {{ .group }}
    kind: {{ .kind }}
    name: {{ .name }}
    namespace: {{ $.Values.namespace }}
  {{- end }}
{{- end }}
